import './globals.css'
import type { Metadata } from 'next'
import { Suspense } from 'react'
import Footer from './section/footer'
import { inter } from './components/typography/fonts'
import { Cols } from './layout/direction'
export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
	}: {
	children: React.ReactNode
	}) {
	return (
		<html lang='en'>
			<body className={`${inter.className} flex bg-bg flex-col justify-between w-full min-h-screen`}>
				<p>Navbar</p>
				<Suspense fallback={<Cols whiteSpaceX className='text-center'>Loadings</Cols>}>
					<main className='h-full px-12'>
						{children}
					</main>
				</Suspense>
				<Footer/>
			</body>
		</html>
	)
}
